---
- name: Deploy Next.js Docker Container
  hosts: all
  become: yes
  vars:
    IMAGE_NAME: "{{ image_name }}"
    DOCKERHUB_USERNAME: "{{ dockerhub_username }}"
    DOCKERHUB_TOKEN: "{{ dockerhub_token }}"
    DOMAIN_NAME: "{{ domain_name }}"
  tasks:
    - name: Run APT update
      ansible.builtin.apt:
        update_cache: yes

    - name: Install Docker and Nginx
      ansible.builtin.apt:
        name: "{{ item }}"
        state: present
      with_items:
        - docker.io
        - nginx

    - name: Start Docker and Nginx
      ansible.builtin.service:
        name: "{{ item }}"
        state: started
      with_items:
        - docker
        - nginx

    - name: Login to Docker Hub with dockerhub_token
      ansible.builtin.docker_login:
        username: "{{ DOCKERHUB_USERNAME }}"
        password: "{{ DOCKERHUB_TOKEN }}"
    
    - name: Pull Docker image
      ansible.builtin.docker_image:
        name: "{{ IMAGE_NAME }}"
        source: pull
    
    - name: Run Docker Container
      ansible.builtin.docker_container:
        name: nextjs_container
        image: "{{ IMAGE_NAME }}"
        state: started
        restart_policy: always
        ports:
          - "3001:3000"
    
    - name: wait for Container to started
      ansible.builtin.wait_for:
        host: localhost
        port: 3001
        delay: 5
        timeout: 60

    - name: Check if Nginx config file exits
      ansible.builtin.stat:
        path: "/etc/nginx/sites-available/{{ DOMAIN_NAME }}"
      register: nginx_config
    
    - name: Configure Nginx
      ansible.builtin.template:
        src: nginx.conf.j2
        dest: "/etc/nginx/sites-available/default"
      when: nginx_config.stat.islnk is not defined
      notify: reload nginx

  handlers:
    - name: reload nginx
      ansible.builtin.service:
        name: nginx
        state: restarted