---
- name: Deploy Next.js Docker Container
  hosts: all
  become: yes
  vars:
    IMAGE_NAME: "{{ image_name }}"
    DOCKERHUB_USERNAME: "{{ dockerhub_username }}"
    DOCKERHUB_TOKEN: "{{ dockerhub_token }}"
    DOMAIN_NAME: "{{ domain_name }}"
  tasks:
    - name: Run APT update
      ansible.builtin.apt:
        update_cache: yes

    - name: Install Docker
      ansible.builtin.apt:
        name: docker.io
        state: present

    - name: Start Docker
      ansible.builtin.service:
        name: docker
        state: started

    - name: Install Nginx
      ansible.builtin.apt:
        name: nginx
        state: present
    
    - name: Start Nginx
      ansible.builtin.service:
        name: nginx
        state: started

    - name: Login to Docker Hub with dockerhub_token
      ansible.builtin.docker_login:
        username: "{{ DOCKERHUB_USERNAME }}"
        password: "{{ DOCKERHUB_TOKEN }}"
    
    - name: Pull Docker image
      ansible.builtin.docker_image:
        name: "{{ IMAGE_NAME }}"
        source: Pull
    
    - name: Run Docker Container
      ansible.builtin.docker_container:
        name: nextjs_container
        image: "{{ IMAGE_NAME }}"
        state: started
        restart_policy: always
        ports:
          - "3001:3000"
    
    - name: wait for Container to started
      ansible.builtin.wait_for:
        host: localost
        port: 3001
        delay: 5
        timeout: 60

    - name: Check if Nginx config file exits
      ansible.builtin.stat:
        path: "/etc/nginx/sites-avaiable/{{ DOMAIN_NAME }}"
      register: nginx_config
    
    - name: Configure Nginx
      ansible.builtin.template:
        src: nginx.conf.j2
        dest: "/etc/nginx/sites-avaiable/default"
      when: not nginx_config.stat.exits
      notify: reload nginx

    - name: Enable Nginx site
      ansible.builtin.file:
        src: "/etc/nginx/sites-avaiable/{{ DOMAIN_NAME }}"
        dest: "/etc/nginx/sites-enabled/{{ DOMAIN_NAME }}"
        state: link
      when: nginx_config.stat.exits
      notify: reload nginx

  handlers:
    - name: reload nginx
      ansible.builtin.service:
        name: nginx
        state: reloaded